version: '3'

services:
  postgressql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - 25672:25672
      - 15672:15672
      - 5672:5672
